cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

core/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, ProductPageView,ContactPageView, cookie_session, cookie_delete

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/',  AboutPageView.as_view(), name="about"),
    path('contact-us/',  ContactPageView.as_view(), name="contact-us"),
    path('testcookie/', cookie_session),
    path('deletecookie/', cookie_delete),
]

machtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('photos/', include('photos.urls')),
    path('products/', include('products.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
    #path autentificación
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #carrito
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductsListView, ProductDetailView, ProductCreate, ProductUpdate, ProductDelete
from . import views

urlpatterns = [
    path('', ProductsListView.as_view(), name='products'),
    path('<int:pk>/<slug:slug>/', ProductDetailView.as_view(), name='product'),
    path('create/',ProductCreate.as_view(),name="create"),
    path('update/<int:pk>/',ProductUpdate.as_view(),name="update"),
    path('delete/<int:pk>/',ProductDelete.as_view(),name="delete"),
]

photos/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Photo(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    photo = models.ImageField(verbose_name="Foto",upload_to="photos",null=True,blank=True)
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "foto"
        verbose_name_plural = "fotos"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    description = models.TextField(verbose_name="Descripción")
    photo = models.ImageField(verbose_name="Foto",upload_to="products",null=True,blank=True,default="/static/core/images/gallery-image-1-1200x800-original.jpg")
    price = models.DecimalField(verbose_name="Precio",max_digits=6,decimal_places=2,blank=False)
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    def time(self):
        tiempo = (self.id-1)*0.15
        return ('{:,.2f}'.format(tiempo))

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"
        ordering = ['order', 'updated']

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields = ['title','description','photo','price','order']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-input'}),
            'description':forms.Textarea(attrs={'class':'form-input'}),
            'photo':forms.ClearableFileInput(attrs={'class':'form-input'}),
            'price':forms.NumberInput(attrs={'class':'form-input'}),
            'order':forms.NumberInput(attrs={'class':'form-input'}),            
        }

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView, HttpResponse

# Create your views here.
class HomePageView(TemplateView):
    template_name = "core/home.html"

class AboutPageView(TemplateView):
    template_name = "core/about.html"

class ProductPageView(TemplateView):
    template_name = "core/products.html"

class ContactPageView(TemplateView):
    template_name = "core/contact-us.html"

def cookie_session(request):
    request.session.set_test_cookie()
    return HttpResponse("<h1>dataflair</h1>")
def cookie_delete(request):
    if request.session.test_cookie_worked():
        request.session.delete_test_cookie()
        response = HttpResponse("dataflair<br> cookie createed")
    else:
        response = HttpResponse("Dataflair <br> Your browser doesnot accept cookies")
    return response

#https://data-flair.training/blogs/django-sessions/

products/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import ProductForm

# Create your views here.
class ProductsListView(ListView):
    model = Product    

class ProductDetailView(DetailView):
    model = Product

class ProductCreate(CreateView):
    model = Product
    form_class=ProductForm
    success_url=reverse_lazy('products')

class ProductUpdate(UpdateView):
    model = Product
    form_class=ProductForm
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse_lazy('update', args=[self.object.id])+"?ok"

class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('products')

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Sobre nosotros{% endblock %}{% endblock %}{% endblock %}
{% block content %}

      <!-- About Me-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left">
            <div class="cell-sm-6 cell-md-5">
              <div class="thumb-bordered"><img src="{% static 'core/images/mt_public.png' %}" alt="" width="437" height="435"/>
              </div>
            </div>
            <div class="cell-sm-6 cell-md-7">
              <div class="box-width-3 box-centered">
                <article class="quote-big">
                  <p class="q">Comprometidos a darte el mejor servicio en desarrollo y diseño.</p>
                </article>
                <div class="divider"></div>
                <p class="text-spacing-05">Nuestro equipo de trabajo completamente capacitados en su rama, desarrolladores, diseñadores, producción audiovisual trabajando juntos para darte la mejor solución.</p>
                <div class="group-3-columns" data-lightgallery="group">
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof1.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof1.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof2.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof2.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof3.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof3.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="es">
  <head>
    <!-- Site Title-->
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'core/images/favicon.ico' %}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700,400italic%7CJosefin+Sans:400,700,300italic">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page Loader-->
    <div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"> </div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="{% url 'home' %}">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'core/images/machtec.svg' %}" alt="" style="width:237px" height="35"/><img class="brand__logo-light" src="images/logo-inverse-237x35.png" alt="" width="237" height="35"/>
                      </div><span class="brand__slogan">diseño y desarrollo</span></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      {% if not request.user.is_authenticated %}
                      <li><a class="icon icon-sm fa fa-sign-in icon-style-camera" href="{% url 'login' %}"><span></span><span></span><span></span><span></span></a></li>
                      {% else %}
                      <li><a class="icon icon-sm fa fa-sign-out icon-style-camera" href="{% url 'logout' %}"><span></span><span></span><span></span><span></span></a></li>
                      {% endif %}
                      {% if LINK_INSTAGRAM %}
                      <li><a class="icon icon-sm fa fa-instagram icon-style-camera" href="{{LINK_INSTAGRAM}}"><span></span><span></span><span></span><span></span></a></li>
                      {% endif %}
                      {% if LINK_FACEBOOK %}
                      <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="{{LINK_FACEBOOK}}"><span></span><span></span><span></span><span></span></a></li>
                      {% endif %}
                      {% if LINK_PINTEREST %}
                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="{{LINK_PINTEREST}}"><span></span><span></span><span></span><span></span></a></li>
                      {% endif %}
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="{% if request.path == '/' %} active {% endif %}"><a href="{% url 'home' %}">Inicio<span></span><span></span><span></span><span></span></a>
                    </li>
                    <li class="{% if request.path == '/about/' %} active {% endif %}"><a href="{% url 'about' %}">Sobre nosotros<span></span><span></span><span></span><span></span></a>
                    </li>
                    <li class="{% if request.path == '/products' %} active {% endif %}"><a href="{% url 'products' %}">Productos<span></span><span></span><span></span><span></span></a>
                    </li>
                    <li class="{% if request.path == '/services' %} active {% endif %}"><a href="{% url 'services' %}">Servicios<span></span><span></span><span></span><span></span></a>
                    </li>
                    <li class="{% if request.path == '/contact-us/' %} active {% endif %}"><a href="{% url 'contact-us' %}">Contáctanos<span></span><span></span><span></span><span></span></a>
                    </li>
                    {% if not request.user.is_authenticated %}
                    <li class="{% if request.path == '/accounts/signup/' %} active {% endif %}"><a href="{% url 'signup' %}">Registrar<span></span><span></span><span></span><span></span></a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>

      {% if request.path != '/' %}
      <!-- Breadcrumbs-->
      <section class="breadcrumbs-custom bg-image" style="background-image: url('/static/core/images/{% block banner %}{% endblock %}');">
        <div class="shell">
          <h1 class="breadcrumbs-custom__title">{% block title1 %}{% endblock %}</h1>
          <ul class="breadcrumbs-custom__path">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li class="active">{% block title2 %}{% endblock %}</li>
          </ul>
        </div>
      </section>
      {% endif %}

      {% block content %}{% endblock %}

      <!-- Page Footer-->
      <footer class="footer-centered section bg-gray-darker">
        <div class="shell">
          <div class="range range-sm-center">
            <div class="cell-sm-10 cell-md-8 cell-lg-6">
              <!-- Brand--><a class="brand" href="{% url 'home' %}">
                <div class="brand__name"><img src="{% static 'core/images/machtec-inverted.png' %}" alt="" width="237" height="35"/>
                </div><span class="brand__slogan">diseño y desarrollo</span></a>
                    <!-- RD Mailform-->
                    <form class="rd-mailform form_inline" data-form-output="form-output-global" data-form-type="subscribe" method="post" action="bat/rd-mailform.php">
                      <div class="form__inner">
                        <div class="form-wrap">
                          <input class="form-input" id="subscribe-form-footer-email" type="email" name="email" data-constraints="@Email @Required">
                          <label class="form-label" for="subscribe-form-footer-email">Su E-mail...</label>
                        </div>
                        <div class="form-button">
                          <button class="button button-link" type="submit">Suscribirse</button>
                        </div>
                      </div>
                    </form>
              <ul class="list-icons list-inline-sm">
                {% if LINK_INSTAGRAM %}
                <li><a class="icon icon-sm fa fa-instagram icon-style-camera" href="{{LINK_INSTAGRAM}}"><span></span><span></span><span></span><span></span></a></li>
                {% endif %}
                {% if LINK_FACEBOOK %}
                <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="{{LINK_FACEBOOK}}"><span></span><span></span><span></span><span></span></a></li>
                {% endif %}
                {% if LINK_PINTEREST %}
                <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="{{LINK_PINTEREST}}"><span></span><span></span><span></span><span></span></a></li>
                {% endif %}
              </ul>
              <!-- Rights-->
              <p class="rights"><span>MachTec</span><span>&nbsp;&copy;&nbsp; </span><span class="copyright-year"></span>.&nbsp; <br class="veil-xs"><a class="link-underline" href="#">Privacy Policy</a><span> Desarrolado&nbsp;por&nbsp;<a>Cristofer Machado</a></span></p>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{% static 'core/js/core.min.js' %}"></script>
    <script src="{% static 'core/js/script.js' %}"></script>
    <!-- coded by Himic-->
  </body>
</html>

core/templates/core/contact-us.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Contáctanos{% endblock %}{% endblock %}{% endblock %}
{% block content %}

      <!-- Get in Touch-->
      <section class="section section-md bg-white text-center">
        <div class="shell">
          <div class="range range-md-center">
            <div class="cell-md-11 cell-lg-10">
              <h2 class="text-bold">Póngase en contacto con nosotros</h2>
              <p><span class="box-width-2">Puede escribirnos a travez de las redes sociales, whatsapp o puede usar este corto formulario para preguntar acerca de nuestros servicios, proyectos o productos.</span></p>
              <div class="layout-columns">
                <div class="layout-columns__main">
                  <div class="layout-columns__main-inner">
                    <!-- RD Mailform-->
                    <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                      <div class="form-wrap">
                        <input class="form-input" id="contact-date" type="text" data-time-picker="date" name="date" data-constraints="@Required">
                        <label class="form-label" for="contact-date">Fecha de reunión</label>
                      </div>
                      <div class="form-wrap">
                        <input class="form-input" id="contact-name" type="text" name="name" data-constraints="@Required">
                        <label class="form-label" for="contact-name">Su nombre</label>
                      </div>
                      <div class="form-wrap">
                        <input class="form-input" id="contact-email" type="email" name="email" data-constraints="@Email @Required">
                        <label class="form-label" for="contact-email">E-mail</label>
                      </div>
                      <div class="form-wrap">
                        <label class="form-label" for="contact-message">Su mensaje</label>
                        <textarea class="form-input" id="contact-message" name="message" data-constraints="@Required"></textarea>
                      </div>
                      <div class="form-wrap form-button offset-1">
                        <button class="button button-block button-primary-outline button-ujarak" type="submit">Enviar mensaje</button>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="layout-columns__aside">
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Redes Sociales</p>
                    <div class="divider-modern"></div>
                    <ul class="list-inline-xs">
                      {% if LINK_FACEBOOK %}
                      <li><a class="icon icon-md icon-gray-7 fa fa-facebook" href="{{LINK_FACEBOOK}}"></a></li>
                      {% endif %}
                      {% if LINK_TWITTER %}
                      <li><a class="icon icon-md icon-gray-7 fa fa-twitter" href="{{LINK_TWITTER}}"></a></li>
                      {% endif %}
                      {% if LINK_GOOGLE %}
                      <li><a class="icon icon-md icon-gray-7 fa fa-google" href="{{LINK_GOOGLE}}"></a></li>
                      {% endif %}
                      {% if LINK_INSTAGRAM %}
                      <li><a class="icon icon-md icon-gray-7 fa fa-instagram" href="{{LINK_INSTAGRAM}}"></a></li>
                      {% endif %}
                      {% if request.user.is_staff %}
                      <li><a class="icon icon-md icon-gray-7 fa fa-edit" href="/admin/social/link/"></a></li>
                      {% endif %}
                    </ul>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Teléfonos</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary material-icons-local_phone"></span></div>
                      <div class="unit__body"><a href="tel:#">1-800-1234-567</a></div>
                    </div>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Dirección</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary material-icons-location_on"></span></div>
                      <div class="unit__body"><a href="#">267 Park Avenue New York, NY 90210</a></div>
                    </div>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Horario</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary mdi mdi-clock"></span></div>
                      <div class="unit__body"><span>Trabajamos todos los dias 9:00–23:00</span></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Inicio{% endblock %}{% endblock %}{% endblock %}
{% block content %}
      {% load photos_carousel %}
      {% get_photo_list as photo_list %}
      <!-- My Best Photos -->
      <section class="section text-center">
        <!-- Slick Carousel-->
        <div class="slick-wrap">
          <div class="slick-slider slick-style-1" data-arrows="true" data-autoplay="true" data-loop="true" data-dots="true" data-swipe="true" data-xs-swipe="true" data-sm-swipe="false" data-items="1" data-sm-items="3" data-md-items="3" data-lg-items="3" data-center-mode="true" data-lightgallery="group-slick">
            {% for photo in photo_list %}
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{{photo.photo.url}}" data-lightgallery="item"><img class="thumb-ann__image" src="{{photo.photo.url}}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">{{photo.title}}</p>
                      <p class="thumb-ann__text">{{photo.content|striptags|safe|truncatechars:"200"}}</p>
                    </div></a>
                </div>
              </div>
            </div>
            {% endfor %}            
          </div>
        </div>
      </section>

      <!-- About Me-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left">
            <div class="cell-sm-6 cell-md-5">
              <div class="thumb-bordered"><img src="{% static 'core/images/mt_public.png' %}" alt="" width="437" height="435"/>
              </div>
            </div>
            <div class="cell-sm-6 cell-md-7">
              <div class="box-width-3 box-centered">
                <article class="quote-big">
                  <p class="q">Comprometidos a darte el mejor servicio en desarrollo y diseño.</p>
                </article>
                <div class="divider"></div>
                <p class="text-spacing-05">Nuestro equipo de trabajo completamente capacitados en su rama, desarrolladores, diseñadores, producción audiovisual trabajando juntos para darte la mejor solución.</p>
                <div class="group-3-columns" data-lightgallery="group">
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof1.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof1.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof2.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof2.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'core/images/prof3.jpg' %}" data-lightgallery="item"><img src="{% static 'core/images/prof3.jpg' %}" alt="" width="120" height="171"/>
                      <div class="thumb-light__overlay"></div></a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

core/templates/core/products.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Productos{% endblock %}{% endblock %}{% endblock %}
{% block content %}

<!-- Products -->
      <section class="section section-md bg-gray-lighter text-center">
        <div class="shell">
          <div class="range range-30">
            <div class="cell-sm-6 cell-md-4 wow fadeInLeftSmall" data-wow-delay="0s">
              <!-- Post boxed-->
              <article class="post-boxed">
                <div class="row">
                  <div class="col-sm-12 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'core/images/gallery-image-1-1200x800-original.jpg' %}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'core/images/gallery-image-1-440x327.jpg' %}" alt="" width="440" height="327"/>
                    <div class="thumb-ruby__caption"> 
                      <p class="thumb-ruby__title heading-3">Image #</p>
                      <p class="thumb-ruby__text">If you are looking for high quality wedding photography, I will be glad to help you.</p>
                    </div></a>
                  </div>
                </div>
                <div class="post-boxed__main">
                  <h3 class="post-boxed__title"><a href="#">Precio: $100.00</a></h3>
                </div>                
              </article>
            </div>
            <div class="cell-sm-6 cell-md-4 wow fadeInLeftSmall" data-wow-delay="0.15s">
              <!-- Post boxed-->
              <article class="post-boxed">
                <div class="row">
                  <div class="col-sm-12 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'core/images/gallery-image-1-1200x800-original.jpg' %}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'core/images/gallery-image-1-440x327.jpg' %}" alt="" width="440" height="327"/>
                    <div class="thumb-ruby__caption"> 
                      <p class="thumb-ruby__title heading-3">Image #</p>
                      <p class="thumb-ruby__text">If you are looking for high quality wedding photography, I will be glad to help you.</p>
                    </div></a>
                  </div>
                </div>
                <div class="post-boxed__main">
                  <h3 class="post-boxed__title"><a href="#">Precio: $100.00</a></h3>
                </div>                
              </article>
            </div>
            <div class="cell-sm-6 cell-md-4 wow fadeInLeftSmall" data-wow-delay="0.3s">
              <!-- Post boxed-->
              <article class="post-boxed">
                <div class="row">
                  <div class="col-sm-12 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'core/images/gallery-image-1-1200x800-original.jpg' %}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'core/images/gallery-image-1-440x327.jpg' %}" alt="" width="440" height="327"/>
                    <div class="thumb-ruby__caption"> 
                      <p class="thumb-ruby__title heading-3">Image #</p>
                      <p class="thumb-ruby__text">If you are looking for high quality wedding photography, I will be glad to help you.</p>
                    </div></a>
                  </div>
                </div>
                <div class="post-boxed__main">
                  <h3 class="post-boxed__title"><a href="#">Precio: $100.00</a></h3>
                </div>                
              </article>
            </div>
          </div>
        </div>
      </section>

{% endblock %}