cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

machtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('photos/', include('photos.urls')),
    path('products/', include('products.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
    #path autentificación
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #carrito
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path
from .views import PhotosListView, PhotoDetailView, PhotoCreate, PhotoUpdate, PhotoDelete
from . import views

urlpatterns = [
    path('', PhotosListView.as_view(), name='photos'),
    path('<int:pk>/<slug:slug>/', PhotoDetailView.as_view(), name='photo'),
    path('create/',PhotoCreate.as_view(),name="createph"),
    path('update/<int:pk>/',PhotoUpdate.as_view(),name="updateph"),
    path('delete/<int:pk>/',PhotoDelete.as_view(),name="deleteph"),
]

photos/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Photo(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    photo = models.ImageField(verbose_name="Foto",upload_to="photos",null=True,blank=True)
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "foto"
        verbose_name_plural = "fotos"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

photos/forms.py
from django import forms
from .models import Photo

class PhotoForm(forms.ModelForm):
    class Meta:
        model=Photo
        fields = ['title','content','order','photo']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control form-input'}),
            'content':forms.Textarea(attrs={'class':'form-control form-input'}),
            'order':forms.NumberInput(attrs={'class':'form-control form-input'}),            
            'photo':forms.ClearableFileInput(attrs={'class':'form-input'}),
        }

photos/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from .models import Photo
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import PhotoForm

# Create your views here.
class PhotosListView(ListView):
    model = Photo

class PhotoDetailView(DetailView):
    model = Photo

class PhotoCreate(CreateView):
    model = Photo
    form_class=PhotoForm
    success_url=reverse_lazy('photos')

class PhotoUpdate(UpdateView):
    model = Photo
    form_class=PhotoForm
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse_lazy('update', args=[self.object.id])+"?ok"

class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('photos')

photos/templates/photos/photo_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Borrar foto{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        
        <div class="cell-sm-10 cell-md-11 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="rd-form" data-form-output="form-output-global" data-form-type="contact" method="post">{% csrf_token %}
                <div class="form-wrap">
                  <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
                </div>                
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Eliminar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

photos/templates/photos/photo_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Agregar foto{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <!-- Image Centered-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range">
            <div class="cell-md-10 cell-lg-8">
              <h2>Image Centered</h2>
              <figure class="figure-light"><img class="img-centered" src="images/typography-1-770x485.jpg" alt="" width="770" height="485"/>
                <figcaption>
                  <p>Wedding Photo</p>
                </figcaption>
              </figure>
              <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our website will find exactly what he/she is looking for. With advanced features of activating account and new login widgets, you will definitely have a great experience of using our web page.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  </section>
{% endblock %}

photos/templates/photos/photo_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Agregar foto{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        
        <div class="cell-sm-10 cell-md-11 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-wrap">
                  <input class="form-input" id="id_title" type="text" name="title" data-constraints="@Required">
                  <label class="form-label" for="id_title">Título</label>
                </div>
                <div class="form-wrap">
                  <label class="" for="id_content">Contenido</label>                  
                  <div class="django-ckeditor-widget" data-field-id="id_content" style="display: inline-block;">
                    <textarea class="form-input" cols="40" id="id_content" name="content" rows="10" required="" data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;es&quot;}" data-external-plugin-resources="[]" data-id="id_content" data-type="ckeditortype" data-constraints="@Required"></textarea>
                  </div>
                </div>
                <div class="form-wrap">
                  <label class="" for="id_photo">Fotografía</label>
                  <input class="form-input" type="file" name="photo" accept="image/*" id="id_photo">                  
                </div>
                <div class="form-wrap">
                  <label class="" for="id_order">Orden</label>
                  <input class="form-input vIntegerField" type="number" name="order" value="0" id="id_order" data-constraints="@Required">                  
                </div>
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Guardar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

photos/templates/photos/photo_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Carrusel de imágenes{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}

      <!-- My Best Photos -->
      <section class="section text-center">
        <!-- Slick Carousel-->
        <div class="slick-wrap">
          <div class="slick-slider slick-style-1" data-arrows="true" data-autoplay="true" data-loop="true" data-dots="true" data-swipe="true" data-xs-swipe="true" data-sm-swipe="false" data-items="1" data-sm-items="3" data-md-items="3" data-lg-items="3" data-center-mode="true" data-lightgallery="group-slick">
            {% for photo in photo_list %}
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{{photo.photo.url}}" data-lightgallery="item"><img class="thumb-ann__image" src="{{photo.photo.url}}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">{{photo.title}}</p>
                      <p class="thumb-ann__text">{{photo.content|striptags|safe|truncatechars:"200"}}</p>
                    </div></a>
                    {% if request.user.is_staff %}
                      <a href="{% url 'updateph' photo.id %}">Editar</a>
                      <a href="{% url 'deleteph' photo.id %}">Borrar</a>
                    {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}            
          </div>
        </div>
      </section>

{% endblock %}

photos/templates/photos/photo_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Modificar foto{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        <div class="cell-sm-10 cell-md-2 wow fadeInRight">
          <div class="box-width-4 box-centered">
            <p class="heading-2">Agrega <br> Tu mejor fotografía</p>
            {% if 'ok' in request.GET %}
            <p style="color:green">
            <a href="{% url 'photos' %}"> Foto Actualizada</a>
            </p>
            {% endif %}
            <p>Pera una mejor visualización agrega una fotografia con buena resolución</p>
          </div>
        </div>
        <div class="cell-sm-10 cell-md-10 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="rd-form" data-form-output="form-output-global" data-form-type="contact" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-wrap">
                  {{ form.as_p }}
                </div>
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Actualizar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}