cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

machtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('photos/', include('photos.urls')),
    path('products/', include('products.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
    #path autentificación
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #carrito
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from .views import ServicesListView, ServiceDetailView, ServiceCreate, ServiceUpdate, ServiceDelete
from . import views

urlpatterns = [
    path('', ServicesListView.as_view(), name='services'),
    path('<int:pk>/<slug:slug>/', ServiceDetailView.as_view(), name='service'),
    path('create/',ServiceCreate.as_view(),name="create"),
    path('update/<int:pk>/',ServiceUpdate.as_view(),name="update"),
    path('delete/<int:pk>/',ServiceDelete.as_view(),name="delete"),
]

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    description = models.TextField(verbose_name="Descripción")
    photo = models.ImageField(verbose_name="Foto",upload_to="products",null=True,blank=True,default="/static/core/images/gallery-image-1-1200x800-original.jpg")
    price = models.DecimalField(verbose_name="Precio",max_digits=6,decimal_places=2,blank=False)
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    def time(self):
        tiempo = (self.id-1)*0.15
        return ('{:,.2f}'.format(tiempo))

    class Meta:
        verbose_name = "servicio"
        verbose_name_plural = "servicios"
        ordering = ['order', 'updated']

    def __str__(self):
        return self.title

services/forms.py
from django import forms
from .models import Service

class ServiceForm(forms.ModelForm):
    class Meta:
        model=Service
        fields = ['title','description','photo','price','order']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-input'}),
            'description':forms.Textarea(attrs={'class':'form-input'}),
            'photo':forms.ClearableFileInput(attrs={'class':'form-input'}),
            'price':forms.NumberInput(attrs={'class':'form-input'}),
            'order':forms.NumberInput(attrs={'class':'form-input'}),            
        }

services/views.py
from django.shortcuts import render, redirect, render_to_response

# Create your views here.
from django.views.generic.list import ListView
from .models import Service
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .forms import ServiceForm
from django.http import HttpResponse

# Create your views here.
class ServicesListView(ListView):
    model = Service

class ServiceDetailView(DetailView):
    model = Service

class ServiceCreate(CreateView):
    model = Service
    form_class=ServiceForm
    success_url=reverse_lazy('services')

class ServiceUpdate(UpdateView):
    model = Service
    form_class=ServiceForm
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse_lazy('update', args=[self.object.id])+"?ok"

class ServiceDelete(DeleteView):
    model = Service
    success_url = reverse_lazy('services')

services/templates/services/service_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Eliminar servicio{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "photos/include/photo_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        
        <div class="cell-sm-10 cell-md-11 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="rd-form" data-form-output="form-output-global" data-form-type="contact" method="post">{% csrf_token %}
                <div class="form-wrap">
                  <p>¿Estás segur@ de que quieres eliminar "{{ object }}"?</p>
                </div>                
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Eliminar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

services/templates/services/service_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Servicio{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "services/include/service_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <!-- Image Centered-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range">
            <div class="cell-md-10 cell-lg-8">
              <h2>{{service.title}}</h2>
              <figure class="figure-light"><img class="img-centered" src="{{service.photo.url}}" alt="" width="770" height="485"/>
                <figcaption>
                  <p>${{service.price}}</p>
                </figcaption>
              </figure>
              <p>{{service.description|safe}}</p>
              {% if request.user.is_staff %}
                <p><a href="{% url 'update' service.id %}">Editar</a></p>
              {% endif %}
            </div>
          </div>
        </div>
      </section>
    </div>
  </section>
{% endblock %}

services/templates/services/service_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Agregar servicio{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "services/include/service_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        
        <div class="cell-sm-10 cell-md-11 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="" data-form-output="form-output-global" data-form-type="contact" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Guardar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

services/templates/services/service_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Servicios{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "services/include/service_menu.html" %}

      <section class="section section-md bg-gray-lighter text-center">
        <div class="shell">
          <div class="range range-30">
          {% for service in service_list %}
            <div class="cell-sm-6 cell-md-4 wow fadeInLeftSmall" data-wow-delay="{{service.time}}s">
              <!-- Post boxed-->
              <article class="post-boxed">
                <div class="row">
                  <div class="col-sm-12 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{{service.photo.url}}" data-lightgallery="item"><img class="thumb-ruby__image" src="{{service.photo.url}}" alt="" width="440" height="327"/>
                    <div class="thumb-ruby__caption"> 
                      <p class="thumb-ruby__title heading-3">{{service.title}}</p>
                      <p class="thumb-ruby__text">{{service.description|striptags|safe|truncatechars:"100"}}</p>
                    </div></a>
                  </div>
                </div>
                <div class="post-boxed__main">
                  <h3 class="post-boxed__title"><a href="#">Precio desde: ${{service.price}}</a></h3>
                  <p><a href="{% url 'service' service.id service.title|slugify %}">Ver más</a></p>
                  <button class="button button-block button-primary-outline button-ujarak" type="">Comprar</button>
                  <a href="{% url 'cart:add_to_cart' service.id %}" >Añadir al carrito</a>
                  {% if request.user.is_staff %}
                    <a href="{% url 'update' service.id %}">Editar</a>
                    <a href="{% url 'delete' service.id %}">Eliminar</a>
                  {% endif %}
                </div>                
              </article>
            </div>
            {% endfor %}
          </div>          
        </div>
      </section>

{% endblock %}

services/templates/services/service_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title2 %}{% block title1 %}{% block title %}Modificar servicio{% endblock %}{% endblock %}{% endblock %}
{% block banner %}collagephotos.jpeg{% endblock %}{% comment %} breadcrumbs-image.jpg {% endcomment %}
{% block content %}
{% include "services/include/service_menu.html" %}
  <!-- Book Your Photo Shoot-->
  <section class="section section-md bg-white">
    <div class="shell">
      <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
        <div class="cell-sm-10 cell-md-2 wow fadeInRight">
          <div class="box-width-4 box-centered">
            {% if 'ok' in request.GET %}
            <p style="color:green">
            <a href="{% url 'service' service.id service.title|slugify %}"> Servicio actualizado</a>
            </p>
            {% endif %}
            <p>Para una mejor visualización agrega una fotografia con buena resolución</p>
          </div>
        </div>
        <div class="cell-sm-10 cell-md-10 wow fadeInLeft">
          <article class="box-line"><span></span><span></span><span></span><span></span>
            <div class="">
              <!-- RD Mailform-->
              <form class="rd-form" data-form-output="form-output-global" data-form-type="contact" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-wrap">
                  {{ form.as_p }}
                </div>
                <div class="form-wrap form-button offset-1">
                  <input class="button button-block button-primary-outline button-ujarak" type="submit" value="Actualizar">
                </div>
              </form>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
{% endblock %}